---
- hosts: all
  become: true
  tasks:
    - name: Install apache
      package:
        name: httpd
        state: present

    - name: start httpd service
      service:
        name: httpd
        state: started
